name: windows

on: [push, pull_request]

permissions: read-all

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-2022, vs: "Visual Studio 2022" }
        - { os: windows-2025-vs2026, vs: "Visual Studio 2026" }

    name: "${{ matrix.config.vs }}"
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - uses: actions/cache@v4
      with:
        path: tensorflow/python
        key: ${{ runner.os }}-${{ runner.arch }}-python-3.12-tensorflow-2.21.0

    - name: Build x64
      shell: bash
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake .. -A x64
        cmake --build . -j 4 --config Release
        ctest --output-on-failure -C Release
        cmake --build . -j 4 --config Debug
        ctest --output-on-failure -C Debug
